baseURL: 'https://ajaib.my.id/'
languageCode: 'en-us'
title: 'Ajaib'
theme: "PaperMod"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'Lebih Bijak, Lebih Cerdas, Lebih Ajaib'
  description: "Sumber informasi harian tentang tips, peluang bisnis, dan perkembangan kripto di Indonesia."
  keywords: [tips bisnis, crypto]
  author: [Me, ajaib]
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.svg"
    favicon16x16: "favicon.svg"
    favicon32x32: "favicon.svg"
    apple_touch_icon: "favicon.svg"
    safari_pinned_tab: "favicon.svg"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  analytics:
    google:
      SiteVerificationTag: "-xd7gN5QFM3JprS3v3840rU-NvkdH6fRbcmj0CfAf6w"

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true

pagination:
  disableAliases: false
  pagerSize: 10