baseURL: 'https://ajaib.my.id/'
languageCode: 'en-us'
title: 'Ajaib'
theme: "PaperMod"

params:
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.svg"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  analytics:
    google:
      SiteVerificationTag: "-xd7gN5QFM3JprS3v3840rU-NvkdH6fRbcmj0CfAf6w"